### PR TITLE
Fix incomplete searchresults when using icingadb module only

### LINKED ISSUE #595: Incomplete searchresults when using icingadb module only
## Describe the bug

When using the icingadb module instead of the monitoring module the searchresults seem to be incomplete.
For example if I search for "msx1pre" the host is diplayed but no services and no Tactical Overview.
But the host has services and I can find them under overview - services.

I think the problem is that the dashlet filter for the services is using:
service.name_ci=\*MSX1PRE\*
And it should be (used to be in the monitoring module):
service.name_ci=\*msx1pre\*|host.name_ci=\*msx1pre\*

This filter logic definitely makes no sense for the Tactical Overview (filters only for "Service Name" although it includes Hosts diagram)

## Expected behavior
All services should be diplayed for the hosts matching the search term.

## Screenshots
search1
services

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.11.1

Loaded Libraries:
icinga/icinga-php-thirdparty 	0.11.0
icinga/icinga-php-library 	0.9.1

Loaded Modules:
director 		1.9.1 	
doc 			2.11.1 	
graphite 		1.2.1 	
icingaclassictheme 		0.5.1
icingadb 		1.0.0 	
incubator 		0.17.0 	
migrate 		2.11.1 	
pdfexport 		0.10.2 	
reactbundle 	0.9.0 	
vspheredb 		1.4.0 	
* Web browser used: Firefox 101.0.1
* Icinga 2 version used (`icinga2 --version`):  r2.13.4-1
* PHP version used (`php --version`): 8.1.8
* Server operating system and version: CentOS Stream release 8

### PR DESCRIPTION
**Pull request by Meister1900**
fixes #595

### CODE REVIEW

**Comment by Meister1900** [comment]
signed the Contributor Agreement

**Comment by krappi01** [comment]
signed CLA

**Comment by nilmerg** [comment]
@cla-bot check

**Comment by bobapple** [comment]
@cla-bot check

**Comment by bobapple** [comment]
@krappi01 cla was signed with username @Meister1900

**Comment by bobapple** [comment]
@cla-bot check

**Pull request closed without merging**
