### PR TITLE
Fix that variable names with dots are interpreted as paths

### LINKED ISSUE #757: Custom variable display
## Describe the bug
Custom variable containing dots is displayed incorrect.

## To Reproduce
Set a customvar like this:
`vars.vhosts = {"xxxxxxxxxxxxx.mgmt.xxxxxx.com"={http_port="443"},}`

## Expected behavior
Display it like in the monitoring module:
image

## Screenshots
Actual display in IcingaDB:
image

## Your Environment
* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.2
* Icinga 2 version (`icinga2 --version`): 2.13.6
* Icinga DB version (`icingadb --version`): 1.1
* PHP version used (`php --version`): 7.3.33
* Server operating system and version: Oracle Linux 7

### PR DESCRIPTION
**Pull request by nilmerg**
fixes #757

### CODE REVIEW

**Comment by nilmerg** [comment]
Tested with: (plus some restrictions)

```
apply Service "with-domain-customvar-names" {
  import "generic-service"

  check_command = "random fortune"
  check_interval = 5m
  retry_interval = 1m

  vars = {
    is_dummy = true
    issue_no = 757
    "example.com" = "abc"
    "ex.ample.com" = "cba"
    "example.0.org" = "xyz"
    "example[1]" = "zyx"
    "real_list" = ["one", "two", "three"]
    "ob" = {
      "je" = {
        "ct" = "tcejbo"
      }
    }
    "ex" = {
      "ample.com" = {
        "bla" = "blub"
      }
    }
    vhosts = {"xxxxxxxxxxxxx.mgmt.xxxxxx.com"={http_port="443"},}
  }

  assign where host.name == "docker-master"
}
```

image

**Review by yhabteab — COMMENTED** [review]
```bash
apply Service "Test" {
    import "generic-service"

    check_command = "random fortune"

    vars = {
      "yonas.de" = null
      "example[1]" = {}
      examples["Joooo"] = []
      examples["Joooo"][0] = []
    }

    assign where host.name == "docker-master"
}
```

Bildschirmfoto 2023-05-26 um 15 36 46

**Database:**
```sql
SELECT * FROM customvar INNER JOIN service_customvar sc on customvar.id = sc.customvar_id INNER JOIN service s on s.id = sc.service_id WHERE s.name='Test'
```
Bildschirmfoto 2023-05-26 um 15 38 01

**Comment by yhabteab** [comment]
**Monitoring:**
Bildschirmfoto 2023-05-26 um 15 42 13

**Comment by nilmerg** [comment]
This is an issue with Icinga DB: https://github.com/Icinga/icingadb/issues/597

**Pull request merged**
