### PR TITLE
configuration.php: Add service grid icon

### PR DESCRIPTION
**Pull request by sukhwinder33445**

### CODE REVIEW

**Comment by sukhwinder33445** [comment]
I actually wanted to add the "th-thumb-empty" icon, but it didn't work. Do you know the reason for this @nilmerg @flourish86 ?

**Comment by nilmerg** [comment]
> I actually wanted to add the "th-thumb-empty" icon, but it didn't work. Do you know the reason for this

Because it [doesn't exist](https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=th-thumb-empty&m=free).

**Comment by nilmerg** [comment]
I'm not sure the `th-` icons even fit for this here. They're usually related to interactable elements (such as sub-menus). Maybe we should still use the icon for services as previously intended?

**Comment by sukhwinder33445** [comment]
You mean this one: 
Screenshot 2021-08-20 at 12 21 57

Should I add it?

**Review by nilmerg — APPROVED** [review]

**Pull request merged**
