### PR TITLE
Account Redis' trademark policy

### PR DESCRIPTION
**Pull request by lippserd**
See https://redis.io/legal/trademark-policy/

### CODE REVIEW

**Comment by lippserd** [comment]
@nilmerg Since I was going over the docs anyway, I took the liberty to fix whitespaces and some arrangements. I can create a separate PR for these changes if necessary.

**Comment by Al2Klimov** [comment]
ImageOptim doesn't pay off – saves <1%. 👍

**Comment by lippserd** [comment]
> @nilmerg Since I was going over the docs anyway, I took the liberty to fix whitespaces and some arrangements. I can create a separate PR for these changes if necessary.

Created a separate PR for the whitespace changes.

**Review by nilmerg — COMMENTED** [review]
What's with `Redis®*`? And the description thing in the footer?

**Comment by lippserd** [comment]
> What's with `Redis®*`? And the description thing in the footer?

Sry, fixed.

**Review by nilmerg — APPROVED** [review]

**Review by nilmerg — APPROVED** [review]

**Pull request merged**
